libraries/compile-examples: support sketch paths outside of workspace
Some code that is used to provide user-friendly paths relative to the root of the repository, rather than unfamiliar absolute paths that expose the full folder structure of the docker container in log messages was written under the assumption that the paths provided by the user to the sketch-paths input will always be within the repository (GITHUB_WORKSPACE). The user may wish to compile example sketches of installed libraries, which are located outside GITHUB_WORKSPACE. Previously, this would result in a workflow failure:

ValueError: '/github/home/Arduino/libraries/FooLibrary/examples/Bar' does not start with '/github/workspace'